### ISSUE TITLE
Create a Code of Conduct Page for this Repository

### ISSUE THREAD

**Issue by tamalchowdhury** [tamalchowdhury/bankcardsbangladesh#1]
Hello dev, this is your first challenge.

Every open-source project needs a Code of Conduct page. Go ahead and comment on this issue, "I want to take this task"

Then once you get approved and accepted, you will be assigned to this task.

Next search online and find a Code of Conduct template.

Edit the template to update with the name with `Bank Cards Bangladesh` as the project name, and `tamalanwaronline@gmail.com` as the contact info.

Then create a new file in your fork `codeofconduct.md` and create a pull request.

**Comment by farhanajuli** [comment]
I want to take this task

**Comment by tamalchowdhury** [comment]
Okay, I just assigned you here.

**Comment by tamalchowdhury** [comment]
Completed with pull request #2
