### ISSUE TITLE
Enhancement----New transition effect on The specific row

### ISSUE THREAD

**Issue by Pritam-2002** [tamalchowdhury/bankcardsbangladesh#24]
**feature**
->When the user hover on the table data it will make a transition effect of making the specific row larger.

**Comment by Pritam-2002** [comment]
@tamalchowdhury if this features seems good then i would like to work on this issue...please check this feature and if it is acceptable then assign me this

**Comment by tamalchowdhury** [comment]
Although, this would make the website pop, I want to avoid this type of effect to keep the design and user experience minimal. So, we don't need it right now.

**Comment by Pritam-2002** [comment]
@tamalchowdhury ok ....anything i can contribute for now?..How about a hero section??
