### ISSUE TITLE
Add new bank info to the README.md file table

### ISSUE THREAD

**Issue by tamalchowdhury** [tamalchowdhury/bankcardsbangladesh#4]
Hello devs, our next task is to create a list of all the banks in Bangladesh and their card offerings. We will do this by collecting publicly available information online and populating the table in the `README.md` file.

Please create a pull request with the new information.

To count for the Hacktoberfest contribution threshold, I require at least 2 bank info/rows to count for one valid contribution.

**Comment by tamalchowdhury** [comment]
Hello @farhanajuli please check out the README.md file, you will see there is a table with the bank information. I have added the first bank, please add the remaining 2. This will count towards your hacktoberfest commits. Please check this image to see where to add the bank info https://prnt.sc/_A4BAciBusAi

Please let me know if you can see your commit showing up on your hacktoberfest.com website account.

Let me know for any help/clarificaion.

**Comment by jobs-code** [comment]
@tamalchowdhury  can I work on this issue ? 

if it is so please assign to me.

**Comment by tamalchowdhury** [comment]
@jobs-code Hi, sorry I haven't seen this comment. Yes you are welcome to work. Right now, you can update the `readme.md` with the new bank info or check out the issues/tasks I have posted. Thanks a lot.
