### ISSUE TITLE
Create a Logo for Bank Cards Bangladesh Open Source Project

### ISSUE THREAD

**Issue by tamalchowdhury** [tamalchowdhury/bankcardsbangladesh#5]
Hello graphic designers! Looking for a logo and graphic for this project. We are going to publish this project as a website and will use the logo as the base for this project, social media graphs, and banners. So please contribute some creativity. As part of the global Hacktoberfest month, we are making this issue to encourage non-coding contributions to open source. Our goal is to help you commit your first contribution to open source software.

Please upload your rough ideas, details, or sketches image as a new comment in this issue. Once we pick a design, we will give your further instructions to how to create a pull request and commit your asset to this repository.

About the project:

## Bank Cards Bangladesh

A list of all bank cards in Bangladesh.
 The goal of this project is to list all the bank cards in one place, so users can make an informed decision when making a bank account. This project is inspired by the public Facebook group: https://www.facebook.com/groups/bcub.bd

Created to learn project management and help beginners get started with #hacktoberfest 2023

**Comment by farhanajuli** [comment]
I want to take the risk

**Comment by tamalchowdhury** [comment]
@farhanajuli I am not assigning you, just submit your draft work and we will see.

**Comment by farhanajuli** [comment]
> @farhanajuli I am not assigning you, just submit your draft work and we will see.

I already did.

**Comment by tamalchowdhury** [comment]
Can you upload an image here?

Host the image in an image hosting site like https://postimages.org/

Then copy the link and embed the image file here, so we can see it. 

This is how to embed an image using HTML img tag

```
<img src="https://i.postimg.cc/J4rt8rWf/burger.jpg" alt="MarineGEO circle logo" style="height: 100px; width:100px;"/>
```

**Comment by tamalchowdhury** [comment]
@farhanajuli please go ahead and create a logo for this site. Have you already created one for this?

**Comment by farhanajuli** [comment]
@tamalchowdhury  I'm on it.

**Comment by farhanajuli** [comment]
@tamalchowdhury  here are the two designs I've made. 

Embedded links:
<img src="https://i.postimg.cc/wx1tXz2G/bank-card-1-1.png" alt="bankCardLogo1" style="height: 100px; width:100px;"/>

<img src="https://i.postimg.cc/pLZ3Vgw2/bank-card-1.png" alt="bankCardLogo2" style="height: 100px; width:100px;"/>
