### ISSUE TITLE
Feature-->How about a dark mode toogle bar 

### ISSUE THREAD

**Issue by Pritam-2002** [tamalchowdhury/bankcardsbangladesh#6]
now days everyone preference dark mode over light mode...

**Comment by Pritam-2002** [comment]
i want to work on this under hacktoberfest if you assign this me ...

**Comment by tamalchowdhury** [comment]
Hello @Pritam-2002 thanks a lot for your interest. We don't have a website at the moment, but we will need one soon. Perhaps you could jump-start this after I assign you. So what do you have in mind? How are you going to build a site for this project? Vanilla or framework? If we use a framework-based started site like Astro, it will have a built-in dark mode option, so it will be easy for us.

Let me know your thoughts and plans on working in this project. So I can assign you tasks.

**Comment by farhanajuli** [comment]
I think a framework will be good for us.

**Comment by Pritam-2002** [comment]
@tamalchowdhury i think it will be best if we use framewroks ...we have to thought a better ui fro this project like creating a navbar footer section ..i will love to work on this websitee..

**Comment by tamalchowdhury** [comment]
Okay, can you please give me a few suggestions? And list their pros and
cons when picking them.

**Comment by farhanajuli** [comment]
I think we can use django framework as backend and react for the frontend. And with django we get a built-in sqlite database which make us easier to handle the database part, as we're storing the bank card information. And with react we can easily handle the frontend part, we can use django-rest framework to create api. Let me know your thoughts @tamalchowdhury

**Comment by tamalchowdhury** [comment]
Hi @farhanajuli, in the scope of this project we will not use a backend. This project can be created with a basic frontend with Vanilla HTML, CSS, or React. We will not use any bank card user information, so no need to use a database. All the data we will display are read-only and want public access.

**Comment by farhanajuli** [comment]
@tamalchowdhury  Ok, sure. So let's create the project. I'm super excited for this.

**Comment by Pritam-2002** [comment]
@tamalchowdhury yep we can use react and for css part we can use tailwind css..using tailwind css it will be easy to make it responsive and react will make it smooth to manage and tim efficient..i would love to work on the website....

**Comment by tamalchowdhury** [comment]
@Pritam-2002 I created issue #11 for you. Have a look and give it a shot.
